apiVersion: v1
kind: Pod
metadata:
  labels:
    heritage: deis
    name: redis
    redis-sentinel: "true"
    role: master
    bootstrap: "true"
  name: redis-master
spec:
  containers:
    - name: master
      image: "tangfeixiong/redis:0.0.1-20160602233602"
      env:
        - name: MASTER
          value: "true"
        - name: DEBUG
          value: "1"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: "tangfeixiong/redis:0.0.1-20160602233602"
      env:
        - name: SENTINEL
          value: "true"
        - name: DEBUG
          value: "1"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      emptyDir: {}
